import { describe, expect, it } from "vitest";
import { calculateAnacNotificationDueDate, evaluateAccumulation, evaluateMultiAirportAccumulation, evaluateSafetyCommitteeApplicability, evaluateSafetyCommitteeComposition, evaluateStaffingCoverage, resolveNotificationStatus, type RegulatoryProfileContext } from "@/server/governance/domain";

const profile = (operationalClass: RegulatoryProfileContext["operationalClass"], operatesRegularRBAC121: boolean | null = false, operatesRegularRBAC135: boolean | null = false): RegulatoryProfileContext => ({ operationalClass, operatesRegularRBAC121, operatesRegularRBAC135 });
const pair = (operationalClass: RegulatoryProfileContext["operationalClass"]) => evaluateAccumulation({ profile: profile(operationalClass), candidateRoleCode: "SAFETY_MANAGER", existingActiveRoleCodes: ["ACCOUNTABLE_MANAGER"] });
const at = new Date("2026-08-29T12:00:00Z");
const period = { effectiveFrom: new Date("2026-01-01"), effectiveTo: null };

describe("Auditoria normativa final da Etapa 03", () => {
  it("GOV-AUD-01 — Classe II proíbe acumulação Gestor Responsável e Safety Manager", () => expect(pair("CLASS_II").decision).toBe("PROHIBITED"));
  it("GOV-AUD-02 — Classe III proíbe acumulação Gestor Responsável e Safety Manager", () => expect(pair("CLASS_III").decision).toBe("PROHIBITED"));
  it("GOV-AUD-03 — Classe IV proíbe acumulação Gestor Responsável e Safety Manager", () => expect(pair("CLASS_IV").decision).toBe("PROHIBITED"));
  it("GOV-AUD-04 — Classe III com menos de três profissionais gera recomendação, sem bloqueio", () => expect(evaluateStaffingCoverage({ profile: profile("CLASS_III"), activeDesignations: [{ userId: "u1", regulatoryRoleCode: "ACCOUNTABLE_MANAGER" }, { userId: "u2", regulatoryRoleCode: "SAFETY_MANAGER" }] }).decision).toBe("RECOMMENDATION"));
  it("GOV-AUD-05 — Classe IV gera recomendação para outras acumulações", () => expect(evaluateAccumulation({ profile: profile("CLASS_IV"), candidateRoleCode: "OPERATIONS_MANAGER", existingActiveRoleCodes: ["MAINTENANCE_MANAGER"] }).decision).toBe("RECOMMENDATION"));
  it("GOV-AUD-06 — Classe I com RBAC 121 admite livre acumulação", () => expect(evaluateAccumulation({ profile: profile("CLASS_I", true, false), candidateRoleCode: "SAFETY_MANAGER", existingActiveRoleCodes: ["ACCOUNTABLE_MANAGER"] }).decision).toBe("ALLOWED"));
  it("GOV-AUD-07 — Classe I com RBAC 135 admite livre acumulação", () => expect(evaluateAccumulation({ profile: profile("CLASS_I", false, true), candidateRoleCode: "SAFETY_MANAGER", existingActiveRoleCodes: ["ACCOUNTABLE_MANAGER"] }).decision).toBe("ALLOWED"));
  it("GOV-AUD-08 — multi-aeródromo distingue livre acumulação de recomendação", () => { expect(evaluateMultiAirportAccumulation(profile("CLASS_I")).decision).toBe("ALLOWED"); expect(evaluateMultiAirportAccumulation(profile("CLASS_II")).decision).toBe("RECOMMENDATION"); });
  it("GOV-AUD-09 — prazo de comunicação à ANAC é calculado em 30 dias", () => expect(calculateAnacNotificationDueDate(new Date("2026-08-01T00:00:00Z")).toISOString()).toBe("2026-08-31T00:00:00.000Z"));
  it("GOV-AUD-10 — pendência vencida é apresentada como atrasada", () => expect(resolveNotificationStatus({ status: "PENDING", dueDate: new Date("2026-08-01"), notifiedAt: null, at }).toString()).toBe("OVERDUE"));
  it("GOV-AUD-11 — envio somente é confirmado quando possui registro explícito", () => expect(resolveNotificationStatus({ status: "SUBMITTED", dueDate: new Date("2026-08-01"), notifiedAt: new Date("2026-08-01"), at })).toBe("SUBMITTED"));
  it("GOV-AUD-12 — CSO é obrigatória no regime SGSO", () => expect(evaluateSafetyCommitteeApplicability("SGSO").decision).toBe("REQUIRED"));
  it("GOV-AUD-13 — CSO sem todos os responsáveis aplicáveis fica incompleta", () => expect(evaluateSafetyCommitteeComposition({ applicability: "REQUIRED", profile: profile("CLASS_II"), at, designations: [{ ...period, userId: "u1", status: "ACTIVE", regulatoryRoleCode: "ACCOUNTABLE_MANAGER" }], members: [{ ...period, userId: "u1", status: "ACTIVE", memberType: "REQUIRED_MEMBER" }] }).decision).toBe("INCOMPLETE"));
  it("GOV-AUD-14 — responsáveis obrigatórios e membro adicional formam estrutura compatível", () => { const roles = ["ACCOUNTABLE_MANAGER", "SAFETY_MANAGER", "OPERATIONS_MANAGER", "MAINTENANCE_MANAGER", "EMERGENCY_RESPONSE_MANAGER"]; expect(evaluateSafetyCommitteeComposition({ applicability: "REQUIRED", profile: profile("CLASS_II"), at, designations: roles.map((regulatoryRoleCode, i) => ({ ...period, userId: `u${i}`, status: "ACTIVE" as const, regulatoryRoleCode })), members: [...roles.map((_, i) => ({ ...period, userId: `u${i}`, status: "ACTIVE" as const, memberType: "REQUIRED_MEMBER" as const })), { ...period, userId: "extra", status: "ACTIVE", memberType: "ADDITIONAL_MEMBER" }] }).decision).toBe("COMPLIANT_STRUCTURE"); });
  it("GOV-AUD-15 — papel sistêmico sem designação não satisfaz composição obrigatória", () => expect(evaluateSafetyCommitteeComposition({ applicability: "REQUIRED", profile: profile("CLASS_I", false, true), at, designations: [], members: [{ ...period, userId: "system-admin", status: "ACTIVE", memberType: "REQUIRED_MEMBER" }] }).decision).toBe("INCOMPLETE"));
});
