import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ airportFindFirst: vi.fn(), versionFindFirst: vi.fn(), versionUpdate: vi.fn(), approvalCreate: vi.fn(), audit: vi.fn(), authority: vi.fn() }));
vi.mock("@/server/audit/service", () => ({ recordAuditEvent: mocks.audit }));
vi.mock("@/server/governance/service", () => ({ canPerformRegulatoryAction: mocks.authority }));
vi.mock("@/server/db", () => ({ db: { airport: { findFirst: mocks.airportFindFirst }, safetyPolicyVersion: { findFirst: mocks.versionFindFirst }, $transaction: vi.fn(async (callback: (tx: unknown) => unknown) => callback({ safetyPolicyVersion: { findFirst: mocks.versionFindFirst, update: mocks.versionUpdate }, safetyPolicyApproval: { create: mocks.approvalCreate } })) } }));
import type { AuthorizationContext } from "@/server/authorization/policies";
import { activateSafetyPolicyVersion, approveSafetyPolicyVersion } from "@/server/safety-policy/service";
const authz: AuthorizationContext = { userId: "manager", organizations: [{ organizationId: "org-a", role: "AIRPORT_ADMIN", airports: [{ organizationId: "org-a", airportId: "airport-a", role: "AIRPORT_ADMIN" }] }] };
const scope = { actor: { id: "session", userId: "manager" }, authz, organizationId: "org-a", airportId: "airport-a", userId: "manager" };
const reviewVersion = { id: "version-2", airportId: "airport-a", version: 2, status: "UNDER_REVIEW" as const };
describe("Etapa 04 — serviços e auditoria", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.airportFindFirst.mockResolvedValue({ id: "airport-a" }); mocks.versionFindFirst.mockResolvedValue(reviewVersion); mocks.authority.mockResolvedValue({ decision: "ALLOWED", rationale: "Designação válida", designationId: "designation-am", regulatoryRoleCode: "ACCOUNTABLE_MANAGER" }); mocks.approvalCreate.mockResolvedValue({ id: "approval-1", policyVersionId: "version-2", approvedBy: "manager", approvedAt: new Date("2026-08-31T12:00:00Z") }); mocks.versionUpdate.mockResolvedValue({ ...reviewVersion, status: "APPROVED" }); });
  it("POL-05 — aprovação preserva approvedBy e approvedAt", async () => { const approvedAt = new Date("2026-08-31T12:00:00Z"); const result = await approveSafetyPolicyVersion(scope, "version-2", { rationale: "Revisão concluída" }, approvedAt); expect(mocks.approvalCreate).toHaveBeenCalledWith({ data: expect.objectContaining({ approvedBy: "manager", approvedAt, policyVersionId: "version-2", regulatoryDesignationId: "designation-am" }) }); expect(result.approval.id).toBe("approval-1"); });
  it("POL-20 — Audit Log registra aprovação", async () => { await approveSafetyPolicyVersion(scope, "version-2", { rationale: "Revisão concluída" }); expect(mocks.audit).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: "SAFETY_POLICY_APPROVED", userId: "manager", organizationId: "org-a", airportId: "airport-a", entityId: "version-2" })); });
  it("POL-21 — Audit Log registra supersession", async () => { const candidate = { id: "version-2", airportId: "airport-a", status: "APPROVED" as const, effectiveFrom: null }; const prior = { id: "version-1", airportId: "airport-a", status: "ACTIVE" as const, effectiveFrom: new Date("2026-01-01") }; mocks.versionFindFirst.mockResolvedValueOnce(candidate).mockResolvedValueOnce(prior); mocks.versionUpdate.mockImplementation(async ({ where, data }: { where: { id: string }; data: Record<string, unknown> }) => ({ ...(where.id === "version-1" ? prior : candidate), ...data })); await activateSafetyPolicyVersion(scope, "version-2", new Date("2026-09-01")); expect(mocks.audit).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: "SAFETY_POLICY_SUPERSEDED", entityId: "version-1", metadata: { supersededBy: "version-2" } })); });
});
