type Objective = { id: string; title: string; description: string; intendedOutcome: string; measureCriterion: string; targetValue: string | null; unit: string | null; status: string; dueDate: string; owner: { name: string } };
type Version = { id: string; version: number; status: string; effectiveFrom: string | null; effectiveTo: string | null; formalStatement: string; organizationCommitments: string; responsibilities: string; resourceCommitment: string; applicableRequirementsCommitment: string; continuousImprovementCommitment: string; safetyReportingPrinciples: string | null; approval: null | { approvedAt: string; authorityCode: string; approver: { name: string } }; reviews: Array<{ id: string; reviewedAt: string; nextReviewAt: string | null; reason: string; result: string }>; communications: Array<{ id: string; audienceScope: string; communicationMethod: string; communicatedAt: string; evidenceReference: string }>; objectives: Objective[] };
export function SafetyPolicyWorkspace({ airportName, versions, previewMode = false }: { airportName: string; versions: Version[]; previewMode?: boolean }) {
  const active = versions.find((item) => item.status === "ACTIVE") ?? versions[0];
  return <><p className="eyebrow">Configurações · {airportName}</p><h1>Política e Objetivos da Segurança Operacional</h1>{previewMode && <p className="preview-notice">Conteúdo demonstrativo somente para leitura. Nenhum dado é persistido.</p>}{!active ? <div className="card"><p className="muted">Ainda não existe uma versão da política neste aeródromo.</p></div> : <>
    <div className="grid two"><section className="card"><p className="eyebrow">Versão {active.version} · {active.status}</p><h2>Declaração formal</h2><p>{active.formalStatement}</p><h3>Compromissos</h3><p>{active.organizationCommitments}</p><h3>Responsabilidades</h3><p>{active.responsibilities}</p></section><section className="card"><h2>Controle documental</h2><p><strong>Vigência:</strong> {active.effectiveFrom ? new Date(active.effectiveFrom).toLocaleDateString("pt-BR", { timeZone: "UTC" }) : "não iniciada"}</p><p><strong>Aprovação:</strong> {active.approval ? `${active.approval.approver.name} · ${new Date(active.approval.approvedAt).toLocaleDateString("pt-BR")}` : "pendente"}</p><p><strong>Autoridade:</strong> {active.approval?.authorityCode ?? "—"}</p><p><strong>Revisões:</strong> {active.reviews.length}</p><p><strong>Comunicações:</strong> {active.communications.length}</p></section></div>
    <section className="card"><h2>Compromissos estruturados</h2><div className="grid two"><div><h3>Recursos</h3><p>{active.resourceCommitment}</p><h3>Requisitos aplicáveis</h3><p>{active.applicableRequirementsCommitment}</p></div><div><h3>Melhoria contínua</h3><p>{active.continuousImprovementCommitment}</p><h3>Relatos de segurança</h3><p>{active.safetyReportingPrinciples ?? "Não informado nesta versão."}</p></div></div></section>
    <section className="card"><h2>Objetivos da segurança operacional</h2><p className="muted">Objetivos gerenciais mensuráveis; não representam SPI, SPT ou ALoSP.</p>{active.objectives.length === 0 ? <p>Nenhum objetivo vinculado.</p> : active.objectives.map((objective) => <article key={objective.id} className="record"><p className="eyebrow">{objective.status} · até {new Date(objective.dueDate).toLocaleDateString("pt-BR", { timeZone: "UTC" })}</p><h3>{objective.title}</h3><p>{objective.description}</p><p><strong>Resultado pretendido:</strong> {objective.intendedOutcome}</p><p><strong>Critério:</strong> {objective.measureCriterion}{objective.targetValue ? ` · ${objective.targetValue} ${objective.unit ?? ""}` : ""}</p><p><strong>Responsável:</strong> {objective.owner.name}</p></article>)}</section>
    <section className="card"><h2>Histórico de versões</h2>{versions.map((version) => <p key={version.id}>Versão {version.version} · {version.status} · {version.effectiveFrom ? new Date(version.effectiveFrom).toLocaleDateString("pt-BR", { timeZone: "UTC" }) : "sem vigência"}</p>)}</section>
  </>}</>;
}
